config/routes.rb
Rails.application.routes.draw do

  get 'about_me/:lang' => 'resume#index'

  post 'robotic_farm/import'    => 'robotic_farm#import'
  get  'robotic_farm(/:group_id)' => 'robotic_farm#index'

  get 'video_stream/index'

  get 'money_note' => 'money_note#index'
  get 'money_note/history/:year/:month' => 'money_note#history'
  get 'money_note/rate/:year/:month' => 'money_note#rate'
  get 'money_note/edit/:id' => 'money_note#edit'
  post 'money_note/update'
  post 'money_note/create'
  post 'money_note/items'

  get 'movie/index'
  get 'movie/reserve'
  post 'movie/reserve_new'
  post 'movie/reserve_delete'
  get 'movie/theater'     => 'movie#theater'
  get 'movie/theater/:id' => 'movie#theater'
  get 'movie/schedule/:id' => 'movie#schedule'
  post 'movie/update_schedules'
  post 'movie/create'
  post 'movie/delete'

  get  'logger/index'
  get  'logger/history/:page' => 'logger#history'
  get  'logger/varify/:page' => 'logger#varify_password_history'

  get 'photo_album/photoset/:path' => 'photo_album#index'
  get 'photo_album/manage'
  get 'photo_album/new'
  post 'photo_album/create'
  post 'photo_album/update'
  post 'photo_album/delete/:path' => 'photo_album#delete'
  get 'photo_album/edit/:path' => 'photo_album#edit'

  get 'video_stream/:id' => 'video_stream#index'
  get 'video_stream' => 'video_stream#index'

  get 'bookmark/manage'
  get 'bookmark/new'
  post 'bookmark/create'
  post 'bookmark/update'
  post 'bookmark/delete/:id' => 'bookmark#delete'
  get 'bookmark/edit/:id' => 'bookmark#edit'

  get   'top/index'
  get   'top/login'
  post  'top/varify'
  get   'top/logout'
  get   'top/first'
  post  'top/record_name'

  get   'lottery/history/:type/:page'    => 'lottery#index'
  get   'lottery/statistic/:type'        => 'lottery#statistic'
  get   'lottery/bubblechart/:type'      => 'lottery#bubble_chart'
  get   'lottery/association_rule/:type' => 'lottery#association_rule'
  get   'lottery/suggestion'             => 'lottery#suggestion'
  get   'lottery/newest/:type'           => 'lottery#newest'
  post  'lottery/new'                    => 'lottery#new'

  post  'weather/update'        => 'weather#update'

  get   'drink/index'           => 'drink#index'
  post  'drink/update'          => 'drink#update'

  get   'foodmenu/index/:type'  => 'food_menu#index'
  post  'foodmenu/update/:type' => 'food_menu#update'

  root 'top#index'

end

app/controllers/video_stream_controller.rb
class VideoStreamController < ApplicationController
    def index

        movie_path = '/kaoru_videos/videos'

        @files = []
        bf_files = []
        flag = false
        Dir.foreach(Rails.public_path.to_s+movie_path) do |f|
            next if f[0]=='.'

            id = File.basename(f,'.*')
            flag = true if !params[:id].nil? and params[:id]==id and !flag

            unless flag
                bf_files << id
            else
                @files << id
            end
        end

        @files.concat(bf_files)

        # move the first to last
        first = @files.shift
        @files << first

        if params[:id].nil?
            @movie_url = "#{movie_path}/#{@files[-1]}.mp4"
        else
            @movie_url = "#{movie_path}/#{params[:id]}.mp4"
        end
    end
end

app/helpers/video_stream_helper.rb
module VideoStreamHelper
end

app/views/video_stream/index.html.erb
<style>
.img_wrap
{
    padding: 3px;
    border: 1px solid #D8D8D8;
    margin: 3px;
    width: 200px;
    height: 112px;
    text-align: center;
    vertical-align:middle;
}

.img_link
{
}

.img_src
{
    max-width: 100%;
    max-height: 100%;
}


#rightside_bar
{
    height: 700px;
    overflow-x: auto;
    overflow-y: auto;
}

#id_video
{
    z-index: 1;
    height: 100%;
    margin-left: auto;
    margin-right: auto;
    background-color: black;
}

#main_panel
{
    z-index: -1;
    height: 600px;
    width: 100%;
    background-color: black;
    text-align:center;
}

</style>

<div class="container-fluid">

    <div class="page-header">
        <h1><small>The videos of </small>Kaoru</h1>
    </div>

    <div class="row">

        <div class="col-md-10" >
            <div class="btn-group" role="group">
                <button id="btn_prev" type="button" class="btn btn-default"><span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span></button>
                <button id="btn_repeat" type="button" class="btn btn-default"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></span></button>
                <button id="btn_next" type="button" class="btn btn-default"><span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span></button>
            </div>

            <br>
            <br>

            <div id="main_panel">
                <video id="id_video" controls autoplay preload="auto" src="<%= full_url(@movie_url) %>"></video>
            </div>
        </div>

        <div id="rightside_bar" class="col-md-2">
            <% @files.each do |f| %>
                <% mov_src = video_stream_path+"/#{f}" %>
                <div class="img_wrap">
                    <a id="<%=f%>" href="<%= mov_src %>" class="img_link" >
                        <% img_src = "/kaoru_videos/images/#{f}.jpg" %>
                        <img src="<%= full_url(img_src) %>" class="img_src">
                    </a>
                </div>
            <% end %>
        </div>

    </div>
</div>

<script language="javascript">
$(document).ready(ready);


function ready()
{console.log(arguments.callee.name);

    $('#id_video').bind('ended', onEnded);

    $(document).on('mouseover', '.img_wrap', onPhotoOver);

    $(document).on('click', '#btn_prev', onPrev);
    $(document).on('click', '#btn_repeat', onRepeat);
    $(document).on('click', '#btn_next', onNext);

    window.location = "#id_video";
}

function onRepeat()
{console.log(arguments.callee.name);
    var ref = $(".img_link").last().prop("href");
    //console.log(ref);
    window.location = ref;
}

function onNext()
{console.log(arguments.callee.name);
    var ref = $(".img_link").first().prop("href");
    //console.log(ref);
    window.location = ref;
}

function onPrev()
{console.log(arguments.callee.name);
    var cnt = $(".img_link").length;
    var ref = $(".img_link").eq(cnt-2).prop("href");
    //console.log(ref);
    window.location = ref;
}


function onEnded()
{console.log(arguments.callee.name);
    onNext();
}

function onPhotoOver()
{
    $(this).transition({
        scale: [1.2, 1.2],
        complete: onPhotoLeave
    });
}

function onPhotoLeave()
{
    $(this).transition({
        scale: [1, 1],
    });
}


function unload()
{

}

</script>